# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(455, 176)
        self.centralwidget = QtWidgets.QWidget(Main)
        self.centralwidget.setObjectName("centralwidget")
        self.c_title = QtWidgets.QLabel(self.centralwidget)
        self.c_title.setGeometry(QtCore.QRect(100, 0, 221, 31))
        self.c_title.setBaseSize(QtCore.QSize(10, 100))
        self.c_title.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.c_title.setAlignment(QtCore.Qt.AlignCenter)
        self.c_title.setObjectName("c_title")
        self.startTime = QtWidgets.QTimeEdit(self.centralwidget)
        self.startTime.setGeometry(QtCore.QRect(100, 70, 81, 20))
        self.startTime.setObjectName("startTime")
        self.endTime = QtWidgets.QTimeEdit(self.centralwidget)
        self.endTime.setGeometry(QtCore.QRect(270, 70, 81, 20))
        self.endTime.setObjectName("endTime")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 70, 60, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(210, 70, 60, 16))
        self.label_2.setObjectName("label_2")
        self.day1 = QtWidgets.QCheckBox(self.centralwidget)
        self.day1.setGeometry(QtCore.QRect(40, 40, 41, 16))
        self.day1.setObjectName("day1")
        self.day2 = QtWidgets.QCheckBox(self.centralwidget)
        self.day2.setGeometry(QtCore.QRect(90, 40, 41, 16))
        self.day2.setObjectName("day2")
        self.day4 = QtWidgets.QCheckBox(self.centralwidget)
        self.day4.setGeometry(QtCore.QRect(190, 40, 51, 16))
        self.day4.setObjectName("day4")
        self.day3 = QtWidgets.QCheckBox(self.centralwidget)
        self.day3.setGeometry(QtCore.QRect(140, 40, 41, 16))
        self.day3.setObjectName("day3")
        self.day6 = QtWidgets.QCheckBox(self.centralwidget)
        self.day6.setGeometry(QtCore.QRect(290, 40, 41, 16))
        self.day6.setObjectName("day6")
        self.day5 = QtWidgets.QCheckBox(self.centralwidget)
        self.day5.setGeometry(QtCore.QRect(240, 40, 41, 16))
        self.day5.setObjectName("day5")
        self.day7 = QtWidgets.QCheckBox(self.centralwidget)
        self.day7.setGeometry(QtCore.QRect(340, 40, 41, 16))
        self.day7.setObjectName("day7")
        self.startTask = QtWidgets.QToolButton(self.centralwidget)
        self.startTask.setGeometry(QtCore.QRect(10, 110, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.startTask.setFont(font)
        self.startTask.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.startTask.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.startTask.setStyleSheet("background:rgb(18, 186, 0)")
        self.startTask.setObjectName("startTask")
        self.checkIn = QtWidgets.QPushButton(self.centralwidget)
        self.checkIn.setGeometry(QtCore.QRect(270, 120, 91, 31))
        self.checkIn.setObjectName("checkIn")
        self.checkOut = QtWidgets.QPushButton(self.centralwidget)
        self.checkOut.setGeometry(QtCore.QRect(360, 120, 91, 31))
        self.checkOut.setObjectName("checkOut")
        Main.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 455, 23))
        self.menubar.setObjectName("menubar")
        Main.setMenuBar(self.menubar)

        self.retranslateUi(Main)
        self.startTask.clicked.connect(Main.on_startTask_click)
        self.checkIn.clicked.connect(Main.on_checkIn_click)
        self.checkOut.clicked.connect(Main.on_checkOut_click)
        self.startTime.timeChanged['QTime'].connect(Main.on_startTime_click)
        self.endTime.timeChanged['QTime'].connect(Main.on_endTime_click)
        self.day1.clicked['bool'].connect(Main.on_day1_click)
        self.day2.clicked['bool'].connect(Main.on_day2_click)
        self.day3.clicked['bool'].connect(Main.on_day3_click)
        self.day4.clicked['bool'].connect(Main.on_day4_click)
        self.day5.clicked['bool'].connect(Main.on_day5_click)
        self.day6.clicked['bool'].connect(Main.on_day6_click)
        self.day7.clicked['bool'].connect(Main.on_day7_click)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "MainWindow"))
        self.c_title.setText(_translate("Main", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">腾讯内部签入签出系统</span></p></body></html>"))
        self.label.setText(_translate("Main", "签入时间："))
        self.label_2.setText(_translate("Main", "签出时间："))
        self.day1.setText(_translate("Main", "周一"))
        self.day2.setText(_translate("Main", "周二"))
        self.day4.setText(_translate("Main", "周四"))
        self.day3.setText(_translate("Main", "周三"))
        self.day6.setText(_translate("Main", "周六"))
        self.day5.setText(_translate("Main", "周五"))
        self.day7.setText(_translate("Main", "周日"))
        self.startTask.setText(_translate("Main", "定时任务"))
        self.checkIn.setText(_translate("Main", "签入"))
        self.checkOut.setText(_translate("Main", "签出"))

